# Generated by Django 3.0.4 on 2020-04-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMBD', '0002_auto_20200407_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielinks',
            old_name='type_movie',
            new_name='type',
        ),
    ]
