# Generated by Django 3.0.4 on 2020-04-12 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IMBD', '0007_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 17, 16, 15, 414216, tzinfo=utc)),
        ),
    ]
